# Default Theme

if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=$DRH
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=$DRS
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=$DLH
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=$DLS
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'0'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}


# Format: segment_name background_color foreground_color [non_default_separator]

window_width=$($TMUX_POWERLINE_DIR_USER_SEGMENTS/../window-width.sh 2>&1)
echo $window_width > /tmp/width

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
    TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=()
    TMUX_POWERLINE_LEFT_STATUS_SEGMENTS+=("tmux_session_info 148 234")
fi

#50

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
    TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=()

    TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS+=("load 237 167")

    if [ "$window_width" -ge 90 ]; then
    TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS+=("date 235 136")
    fi

    if [ "$window_width" -ge 100 ]; then
    TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS+=("date_day 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}")
    fi

    if [ "$window_width" -ge 90 ]; then
    TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS+=("time 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}")
    else
    TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS+=("time 235 136")
    fi
fi
