#! /bin/bash

apt-install () {
  dpkg-query -f '${Status}' -W $1 | grep -E '^(install|hold) ok installed$' || sudo apt install -y $1
}

if type apt >/dev/null 2>&1; then
  apt-install build-essential
  apt-install gcc
  apt-install make
  apt-install automake
  apt-install autoconf
  apt-install pkg-config
  apt-install libncurses-dev
  apt-install libncursesw5-dev
  apt-install libevent-dev
  # ruby
  apt-install libssl-dev
  apt-install libreadline-dev
  apt-install zlib1g-dev
fi
