#! /bin/bash


install () {
  if [ "$(uname)" == 'Darwin' ]; then
    brew install jq
  elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
    cd $HOME/local/bin
    rm jq
    url=$(ruby -e "require 'open-uri';require 'json';puts JSON.parse(open('https://api.github.com/repos/stedolan/jq/releases/latest').read)['assets'].select{|n| n['name']=='jq-linux64'}.first['url']")
    curl -L -H 'Accept: application/octet-stream' $url -O jq
    chmod a+x jq
  else
    echo "Your platform ($(uname -a)) is not supported."
    exit 1
  fi

}

command -v jq >/dev/null 2>&1 || install
