#! /bin/bash

install () {
  if [ "$(uname)" == 'Darwin' ]; then
    brew install tmux
  elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
    OS='linux'

    if type apt >/dev/null 2>&1; then
      sudo apt install -y libevent-dev
    fi

    cd $HOME/local/src
    [ ! -f tmux-3.1.tar.gz ] && wget https://github.com/tmux/tmux/releases/download/3.1/tmux-3.1.tar.gz
    tar -zxf tmux-3.1.tar.gz
    cd tmux-3.1
    ./configure --prefix=/usr/local
    make
    sudo make install
  else
    echo "Your platform ($(uname -a)) is not supported."
    exit 1
  fi
}

command -v tmux >/dev/null 2>&1 || install
tmux -V | grep 3.1 2>&1 >/dev/null || install
cd $HOME && rm -f .tmux.conf && ln -s $HOME/repo/github.com/aki017/dotfiles/tmux.conf ./.tmux.conf
