#! /bin/bash

install () {
  cd $HOME/local/src
  [ ! -f tmux-2.3.tar.gz ] && wget https://github.com/tmux/tmux/releases/download/2.3/tmux-2.3.tar.gz
  tar -zxf tmux-2.3.tar.gz
  cd tmux-2.3
  ./configure --prefix=/usr/local
  make
  sudo make install
}
[ ! -f /usr/local/bin/tmux ] && install
cd $HOME && rm -f .tmux.conf && ln -s $HOME/repo/github.com/aki017/dotfiles/tmux.conf ./.tmux.conf
