#! /bin/bash

install () {
  if [ "$(uname)" == 'Darwin' ]; then
    brew install zsh
  elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
    cd $HOME/local
    [ ! -f zsh-5.2.tar.gz ] && wget https://downloads.sourceforge.net/project/zsh/zsh/5.2/zsh-5.2.tar.gz
    tar -zxf zsh-5.2.tar.gz
    cd zsh-5.2
    ./configure --prefix=/usr/local --enable-cap --enable-maildir-support --enable-multibyte --enable-pcre
    make -j8
    sudo make install
  else
    echo "Your platform ($(uname -a)) is not supported."
    exit 1
  fi
}

command -v zsh >/dev/null 2>&1 || install
zshpath=`command -v zsh`

if ! grep $zshpath /etc/shells >/dev/null ; then
  echo "append zsh to /etc/shells"
  echo $zshpath | sudo tee -a /etc/shells
fi
[ "$SHELL" != "$zshpath" ] && chsh -s $zshpath
cd $HOME && rm -f .zshrc && ln -s $HOME/repo/github.com/aki017/zshrc/zsh ./.zshrc
cd $HOME && rm -f .zshenv && ln -s $HOME/repo/github.com/aki017/zshrc/zshenv ./.zshenv
ghq get -u zsh-users/zsh-syntax-highlighting 
